"""This file is meant to make it easier to handle srcs"""

GENDATA = [
    "GenData/Appl_Cbk.h",
    "GenData/BrsTccCfg.h",
    "GenData/BswM_Cfg.h",
    "GenData/BswM_Lcfg.c",
    "GenData/BswM_MemMap.h",
    "GenData/BswM_Private_Cfg.h",
    "GenData/CanIf_Can.h",
    "GenData/CanIf_CanTrcv.h",
    "GenData/CanIf_Cfg.h",
    "GenData/CanIf_Lcfg.c",
    "GenData/CanIf_MemMap.h",
    "GenData/CanIf_PBcfg.c",
    "GenData/CanSM_Cfg.h",
    "GenData/CanSM_Lcfg.c",
    "GenData/CanTp_Cfg.h",
    "GenData/CanTp_Lcfg.c",
    "GenData/CanTp_Lcfg.h",
    "GenData/CanTp_MemMap.h",
    "GenData/CanTp_PBcfg.c",
    "GenData/CanTp_PBcfg.h",
    "GenData/Can_30_Core_Cfg.h",
    "GenData/Can_30_Core_Lcfg.c",
    "GenData/Can_30_Core_MemMap.h",
    "GenData/Can_30_Core_PBcfg.c",
    "GenData/Can_DrvGeneralTypes.h",
    "GenData/ComM_Cfg.h",
    "GenData/ComM_GenTypes.h",
    "GenData/ComM_Lcfg.c",
    "GenData/ComM_Lcfg.h",
    "GenData/ComM_MemMap.h",
    "GenData/ComM_Private_Cfg.h",
    "GenData/Components/BSW_Handler_MemMap.h",
    "GenData/Components/DemMaster_Invalid_OsApplication_MemMap.h",
    "GenData/Components/DemSatellite_Invalid_OsApplication_MemMap.h",
    "GenData/Components/IoHwAb_MemMap.h",
    "GenData/Components/LightCtrl_MemMap.h",
    "GenData/Components/Os_OsCore_swc_MemMap.h",
    "GenData/Components/Rte_BswM.h",
    "GenData/Components/Rte_BswM_Type.h",
    "GenData/Components/Rte_BSW_Handler.h",
    "GenData/Components/Rte_BSW_Handler_Type.h",
    "GenData/Components/Rte_ComM.h",
    "GenData/Components/Rte_ComM_Type.h",
    "GenData/Components/Rte_Dcm.h",
    "GenData/Components/Rte_Dcm_Type.h",
    "GenData/Components/Rte_DemMaster_Invalid_OsApplication.h",
    "GenData/Components/Rte_DemMaster_Invalid_OsApplication_Type.h",
    "GenData/Components/Rte_DemSatellite_Invalid_OsApplication.h",
    "GenData/Components/Rte_DemSatellite_Invalid_OsApplication_Type.h",
    "GenData/Components/Rte_Det.h",
    "GenData/Components/Rte_Det_Type.h",
    "GenData/Components/Rte_EcuM.h",
    "GenData/Components/Rte_EcuM_Type.h",
    "GenData/Components/Rte_IoHwAb.h",
    "GenData/Components/Rte_IoHwAb_Type.h",
    "GenData/Components/Rte_LightCtrl.h",
    "GenData/Components/Rte_LightCtrl_Type.h",
    "GenData/Components/Rte_NvM.h",
    "GenData/Components/Rte_NvM_Type.h",
    "GenData/Components/Rte_Os_OsCore_swc.h",
    "GenData/Components/Rte_Os_OsCore_swc_Type.h",
    "GenData/ComStack_Cfg.h",
    "GenData/Com_Cbk.h",
    "GenData/Com_Cfg.h",
    "GenData/Com_Cfg_CheckUpdateBit.h",
    "GenData/Com_Cfg_CrossPartitionQueueData.h",
    "GenData/Com_Cfg_DescriptionGatewayData.h",
    "GenData/Com_Cfg_Deserializer.h",
    "GenData/Com_Cfg_EventCache.h",
    "GenData/Com_Cfg_FilterData.h",
    "GenData/Com_Cfg_GwTout.h",
    "GenData/Com_Cfg_Initialization.h",
    "GenData/Com_Cfg_InvalidationData.h",
    "GenData/Com_Cfg_IPduGroupHdlr.h",
    "GenData/Com_Cfg_ISRThreshold.h",
    "GenData/Com_Cfg_LLRxTp.h",
    "GenData/Com_Cfg_LLTxTp.h",
    "GenData/Com_Cfg_ReceptionProcessingData.h",
    "GenData/Com_Cfg_Repetition.h",
    "GenData/Com_Cfg_Reporting.h",
    "GenData/Com_Cfg_RxDlMon.h",
    "GenData/Com_Cfg_RxPduBuffer.h",
    "GenData/Com_Cfg_RxSignalBufferData.h",
    "GenData/Com_Cfg_Serializer.h",
    "GenData/Com_Cfg_SignalGatewayData.h",
    "GenData/Com_Cfg_Timer.h",
    "GenData/Com_Cfg_TransmissionProcessingData.h",
    "GenData/Com_Cfg_TxBuffer.h",
    "GenData/Com_Cfg_TxCyclic.h",
    "GenData/Com_Cfg_TxDlMon.h",
    "GenData/Com_Cfg_TxModeHdlr.h",
    "GenData/Com_Cfg_TxSignalFiltering.h",
    "GenData/Com_Cfg_TxTransmit.h",
    "GenData/Com_Cot.h",
    "GenData/Com_GeneratedMainFunctions.c",
    "GenData/Com_Lcfg.c",
    "GenData/Com_Lcfg.h",
    "GenData/Com_MemMap.h",
    "GenData/Com_PBcfg.c",
    "GenData/Com_PBcfg.h",
    "GenData/Com_Types.h",
    "GenData/Crc_Cfg.h",
    "GenData/Crc_MemMap.h",
    "GenData/Dcm_Cfg.h",
    "GenData/Dcm_Lcfg.c",
    "GenData/Dcm_Lcfg.h",
    "GenData/Dcm_MemMap.h",
    "GenData/Dcm_PBcfg.c",
    "GenData/Dcm_PBcfg.h",
    "GenData/Dem_AdditionalIncludeCfg.h",
    "GenData/Dem_Cfg.h",
    "GenData/Dem_Lcfg.c",
    "GenData/Dem_Lcfg.h",
    "GenData/Dem_MemMap.h",
    "GenData/Dem_PBcfg.c",
    "GenData/Dem_PBcfg.h",
    "GenData/Dem_Swc.h",
    "GenData/Dem_Swc_Types.h",
    "GenData/Det_Cfg.c",
    "GenData/Det_Cfg.h",
    "GenData/Det_MemMap.h",
    "GenData/EcuM_Cfg.c",
    "GenData/EcuM_Cfg.h",
    "GenData/EcuM_Generated_Types.h",
    "GenData/EcuM_Init_Cfg.c",
    "GenData/EcuM_Init_Cfg.h",
    "GenData/EcuM_Init_PBcfg.c",
    "GenData/EcuM_Init_PBcfg.h",
    "GenData/EcuM_MemMap.h",
    "GenData/EcuM_PBcfg.c",
    "GenData/EcuM_PrivateCfg.h",
    "GenData/inc/Adc_Cfg.h",
    "GenData/inc/Adc_PBcfg.h",
    "GenData/inc/Dio_Cfg.h",
    "GenData/inc/Fee_Cfg.h",
    "GenData/inc/Fee_PBcfg.h",
    "GenData/inc/Fls_17_Dmu_Cfg.h",
    "GenData/inc/Fls_17_Dmu_PBcfg.h",
    "GenData/inc/Irq_Cfg.h",
    "GenData/inc/McalLib_Cfg.h",
    "GenData/inc/Mcu_17_TimerIp_Cfg.h",
    "GenData/inc/Mcu_Cfg.h",
    "GenData/inc/Mcu_PBcfg.h",
    "GenData/inc/Port_Cfg.h",
    "GenData/inc/Port_PBcfg.h",
    "GenData/Ioc.h",
    "GenData/MemIf_Cfg.c",
    "GenData/MemIf_Cfg.h",
    "GenData/MemIf_MemMap.h",
    "GenData/MemMap_Common.h",
    "GenData/MemMap_Compatibility.h",
    "GenData/NvM_Cfg.c",
    "GenData/NvM_Cfg.h",
    "GenData/NvM_MemMap.h",
    "GenData/NvM_PrivateCbk.h",
    "GenData/NvM_PrivateCfg.h",
    "GenData/Os_AccessCheck_Cfg.h",
    "GenData/Os_AccessCheck_Lcfg.c",
    "GenData/Os_AccessCheck_Lcfg.h",
    "GenData/Os_Alarm_Cfg.h",
    "GenData/Os_Alarm_Lcfg.c",
    "GenData/Os_Alarm_Lcfg.h",
    "GenData/Os_Application_Cfg.h",
    "GenData/Os_Application_Lcfg.c",
    "GenData/Os_Application_Lcfg.h",
    "GenData/Os_Barrier_Cfg.h",
    "GenData/Os_Barrier_Lcfg.c",
    "GenData/Os_Barrier_Lcfg.h",
    "GenData/Os_Cfg.h",
    "GenData/Os_Compiler_Cfg.h",
    "GenData/Os_Core_Cfg.h",
    "GenData/Os_Core_Lcfg.c",
    "GenData/Os_Core_Lcfg.h",
    "GenData/Os_Counter_Cfg.h",
    "GenData/Os_Counter_Lcfg.c",
    "GenData/Os_Counter_Lcfg.h",
    "GenData/Os_Error_Cfg.h",
    "GenData/Os_Error_Lcfg.c",
    "GenData/Os_Error_Lcfg.h",
    "GenData/Os_Hal_Cfg.h",
    "GenData/Os_Hal_Context_Lcfg.c",
    "GenData/Os_Hal_Context_Lcfg.h",
    "GenData/Os_Hal_Core_Cfg.h",
    "GenData/Os_Hal_Core_Lcfg.c",
    "GenData/Os_Hal_Core_Lcfg.h",
    "GenData/Os_Hal_Entry_Cfg.h",
    "GenData/Os_Hal_Entry_Lcfg.c",
    "GenData/Os_Hal_Entry_Lcfg.h",
    "GenData/Os_Hal_Interrupt_Cfg.h",
    "GenData/Os_Hal_Interrupt_Lcfg.c",
    "GenData/Os_Hal_Interrupt_Lcfg.h",
    "GenData/Os_Hal_Kernel_Lcfg.c",
    "GenData/Os_Hal_Kernel_Lcfg.h",
    "GenData/Os_Hal_Lcfg.h",
    "GenData/Os_Hal_MemoryProtection_Cfg.h",
    "GenData/Os_Hal_MemoryProtection_Lcfg.c",
    "GenData/Os_Hal_MemoryProtection_Lcfg.h",
    "GenData/Os_Hal_Timer_Lcfg.c",
    "GenData/Os_Hal_Timer_Lcfg.h",
    "GenData/Os_Hook_Cfg.h",
    "GenData/Os_Hook_Lcfg.c",
    "GenData/Os_Hook_Lcfg.h",
    "GenData/Os_Interrupt_Cfg.h",
    "GenData/Os_Ioc_Cfg.h",
    "GenData/Os_Ioc_Lcfg.c",
    "GenData/Os_Ioc_Lcfg.h",
    "GenData/Os_Isr_Lcfg.c",
    "GenData/Os_Isr_Lcfg.h",
    "GenData/Os_Lcfg.h",
    "GenData/Os_MemMapInt.h",
    "GenData/Os_MemMap_OsCodeInt.h",
    "GenData/Os_MemMap_OsSectionsInt.h",
    "GenData/Os_MemMap_StacksInt.h",
    "GenData/Os_MemoryProtection_Cfg.h",
    "GenData/Os_MemoryProtection_Lcfg.c",
    "GenData/Os_MemoryProtection_Lcfg.h",
    "GenData/Os_Peripheral_Lcfg.c",
    "GenData/Os_Peripheral_Lcfg.h",
    "GenData/Os_Resource_Lcfg.c",
    "GenData/Os_Resource_Lcfg.h",
    "GenData/Os_Scheduler_Cfg.h",
    "GenData/Os_Scheduler_Lcfg.c",
    "GenData/Os_Scheduler_Lcfg.h",
    "GenData/Os_ScheduleTable_Cfg.h",
    "GenData/Os_ScheduleTable_Lcfg.c",
    "GenData/Os_ScheduleTable_Lcfg.h",
    "GenData/Os_ServiceFunction_Cfg.h",
    "GenData/Os_ServiceFunction_Lcfg.c",
    "GenData/Os_ServiceFunction_Lcfg.h",
    "GenData/Os_Spinlock_Lcfg.c",
    "GenData/Os_Spinlock_Lcfg.h",
    "GenData/Os_Stack_Cfg.h",
    "GenData/Os_Stack_Lcfg.c",
    "GenData/Os_Stack_Lcfg.h",
    "GenData/Os_Task_Lcfg.c",
    "GenData/Os_Task_Lcfg.h",
    "GenData/Os_TimingProtection_Cfg.h",
    "GenData/Os_TimingProtection_Lcfg.c",
    "GenData/Os_TimingProtection_Lcfg.h",
    "GenData/Os_Trace_Cfg.h",
    "GenData/Os_Trace_Lcfg.c",
    "GenData/Os_Trace_Lcfg.h",
    "GenData/Os_Types_Lcfg.h",
    "GenData/Os_XSignal_Cfg.h",
    "GenData/Os_XSignal_Lcfg.c",
    "GenData/Os_XSignal_Lcfg.h",
    "GenData/PduR_CanIf.h",
    "GenData/PduR_CanTp.h",
    "GenData/PduR_Cfg.h",
    "GenData/PduR_Com.h",
    "GenData/PduR_Dcm.h",
    "GenData/PduR_Lcfg.c",
    "GenData/PduR_Lcfg.h",
    "GenData/PduR_MemMap.h",
    "GenData/PduR_PBcfg.c",
    "GenData/PduR_PBcfg.h",
    "GenData/PduR_Types.h",
    "GenData/Rte.c",
    "GenData/Rte.h",
    "GenData/Rte_Cbk.h",
    "GenData/Rte_Cfg.h",
    "GenData/Rte_Compiler_Cfg.h",
    "GenData/Rte_DataHandleType.h",
    "GenData/Rte_Hook.h",
    "GenData/Rte_Main.h",
    "GenData/Rte_MemMap.h",
    "GenData/Rte_Type.h",
    "GenData/Rte_UserTypes.h",
    "GenData/SchM_Adc.h",
    "GenData/SchM_Adc_Type.h",
    "GenData/SchM_BswM.h",
    "GenData/SchM_BswM_Type.h",
    "GenData/SchM_CanIf.h",
    "GenData/SchM_CanIf_Type.h",
    "GenData/SchM_CanSM.h",
    "GenData/SchM_CanSM_Type.h",
    "GenData/SchM_CanTp.h",
    "GenData/SchM_CanTp_Type.h",
    "GenData/SchM_Can_30_Core.h",
    "GenData/SchM_Can_30_Core_Type.h",
    "GenData/SchM_Com.h",
    "GenData/SchM_ComM.h",
    "GenData/SchM_ComM_Type.h",
    "GenData/SchM_Com_Type.h",
    "GenData/SchM_Dcm.h",
    "GenData/SchM_Dcm_Type.h",
    "GenData/SchM_Dem.h",
    "GenData/SchM_Dem_Type.h",
    "GenData/SchM_Det.h",
    "GenData/SchM_Det_Type.h",
    "GenData/SchM_Dio.h",
    "GenData/SchM_Dio_Type.h",
    "GenData/SchM_EcuM.h",
    "GenData/SchM_EcuM_Type.h",
    "GenData/SchM_Fee.h",
    "GenData/SchM_Fee_Type.h",
    "GenData/SchM_Fls_17_Dmu.h",
    "GenData/SchM_Fls_17_Dmu_Type.h",
    "GenData/SchM_Irq.h",
    "GenData/SchM_Irq_Type.h",
    "GenData/SchM_McalLib.h",
    "GenData/SchM_McalLib_Type.h",
    "GenData/SchM_Mcu.h",
    "GenData/SchM_Mcu_Type.h",
    "GenData/SchM_NvM.h",
    "GenData/SchM_NvM_Type.h",
    "GenData/SchM_PduR.h",
    "GenData/SchM_PduR_Type.h",
    "GenData/SchM_Port.h",
    "GenData/SchM_Port_Type.h",
    "GenData/SchM_vCan_30_Mcan.h",
    "GenData/SchM_vCan_30_Mcan_Type.h",
    "GenData/src/Adc_PBcfg.c",
    "GenData/src/Dio_Lcfg.c",
    "GenData/src/Fee_PBcfg.c",
    "GenData/src/Fls_17_Dmu_PBcfg.c",
    "GenData/src/Mcu_17_TimerIp_Cfg.c",
    "GenData/src/Mcu_PBcfg.c",
    "GenData/src/Port_PBcfg.c",
    "GenData/vBrsCfg.h",
    "GenData/vBrs_Lcfg.c",
    "GenData/vBrs_Lcfg.h",
    "GenData/vCan_30_Mcan_Cfg.h",
    "GenData/vCan_30_Mcan_Lcfg.c",
    "GenData/vCan_30_Mcan_MemMap.h",
    "GenData/vCan_30_Mcan_PBcfg.c",
    "GenData/vLinkGen_Cfg.h",
    "GenData/vLinkGen_Lcfg.c",
    "GenData/vLinkGen_Lcfg.h",
    # RTE Analyser
    # "GenData/RteAnalyzer/Source/Adc.c",
    # "GenData/RteAnalyzer/Source/BswM.c",
    # "GenData/RteAnalyzer/Source/BSW_Handler.c",
    # "GenData/RteAnalyzer/Source/CanIf.c",
    # "GenData/RteAnalyzer/Source/CanSM.c",
    # "GenData/RteAnalyzer/Source/CanTp.c",
    # "GenData/RteAnalyzer/Source/Can_30_Core.c",
    # "GenData/RteAnalyzer/Source/Com.c",
    # "GenData/RteAnalyzer/Source/ComM.c",
    # "GenData/RteAnalyzer/Source/Com_Cfg.h",
    # "GenData/RteAnalyzer/Source/Dcm.c",
    # "GenData/RteAnalyzer/Source/Dem.c",
    # "GenData/RteAnalyzer/Source/DemMaster_Invalid_OsApplication.c",
    # "GenData/RteAnalyzer/Source/DemSatellite_Invalid_OsApplication.c",
    # "GenData/RteAnalyzer/Source/Det.c",
    # "GenData/RteAnalyzer/Source/Dio.c",
    # "GenData/RteAnalyzer/Source/EcuM.c",
    # "GenData/RteAnalyzer/Source/Fee.c",
    # "GenData/RteAnalyzer/Source/Fls_17_Dmu.c",
    # "GenData/RteAnalyzer/Source/IoHwAb.c",
    # "GenData/RteAnalyzer/Source/Irq.c",
    # "GenData/RteAnalyzer/Source/LdCom_Cfg.h",
    # "GenData/RteAnalyzer/Source/LightCtrl.c",
    # "GenData/RteAnalyzer/Source/McalLib.c",
    # "GenData/RteAnalyzer/Source/Mcu.c",
    # "GenData/RteAnalyzer/Source/NvM.c",
    # "GenData/RteAnalyzer/Source/NvM_Cfg.h",
    # "GenData/RteAnalyzer/Source/Os_Cfg.h",
    # "GenData/RteAnalyzer/Source/Os_OsCore_swc.c",
    # "GenData/RteAnalyzer/Source/PduR.c",
    # "GenData/RteAnalyzer/Source/Port.c",
    # "GenData/RteAnalyzer/Source/Rtm_Cfg.h",
    # "GenData/RteAnalyzer/Source/TestControl.c",
    # "GenData/RteAnalyzer/Source/TSC_BswM.c",
    # "GenData/RteAnalyzer/Source/TSC_BswM.h",
    # "GenData/RteAnalyzer/Source/TSC_BSW_Handler.c",
    # "GenData/RteAnalyzer/Source/TSC_BSW_Handler.h",
    # "GenData/RteAnalyzer/Source/TSC_ComM.c",
    # "GenData/RteAnalyzer/Source/TSC_ComM.h",
    # "GenData/RteAnalyzer/Source/TSC_Dcm.c",
    # "GenData/RteAnalyzer/Source/TSC_Dcm.h",
    # "GenData/RteAnalyzer/Source/TSC_DemMaster_Invalid_OsApplication.c",
    # "GenData/RteAnalyzer/Source/TSC_DemMaster_Invalid_OsApplication.h",
    # "GenData/RteAnalyzer/Source/TSC_DemSatellite_Invalid_OsApplication.c",
    # "GenData/RteAnalyzer/Source/TSC_DemSatellite_Invalid_OsApplication.h",
    # "GenData/RteAnalyzer/Source/TSC_Det.c",
    # "GenData/RteAnalyzer/Source/TSC_Det.h",
    # "GenData/RteAnalyzer/Source/TSC_EcuM.c",
    # "GenData/RteAnalyzer/Source/TSC_EcuM.h",
    # "GenData/RteAnalyzer/Source/TSC_IoHwAb.c",
    # "GenData/RteAnalyzer/Source/TSC_IoHwAb.h",
    # "GenData/RteAnalyzer/Source/TSC_LightCtrl.c",
    # "GenData/RteAnalyzer/Source/TSC_LightCtrl.h",
    # "GenData/RteAnalyzer/Source/TSC_NvM.c",
    # "GenData/RteAnalyzer/Source/TSC_NvM.h",
    # "GenData/RteAnalyzer/Source/TSC_Os_OsCore_swc.c",
    # "GenData/RteAnalyzer/Source/TSC_Os_OsCore_swc.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Adc.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Adc.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_BswM.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_BswM.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_CanIf.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_CanIf.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_CanSM.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_CanSM.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_CanTp.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_CanTp.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Can_30_Core.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Can_30_Core.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Com.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Com.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_ComM.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_ComM.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Dcm.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Dcm.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Dem.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Dem.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Det.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Det.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Dio.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Dio.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_EcuM.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_EcuM.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Fee.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Fee.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Fls_17_Dmu.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Fls_17_Dmu.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Irq.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Irq.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_McalLib.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_McalLib.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Mcu.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Mcu.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_NvM.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_NvM.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_PduR.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_PduR.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Port.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_Port.h",
    # "GenData/RteAnalyzer/Source/TSC_SchM_vCan_30_Mcan.c",
    # "GenData/RteAnalyzer/Source/TSC_SchM_vCan_30_Mcan.h",
    # "GenData/RteAnalyzer/Source/vCan_30_Mcan.c",
]

SOURCE = [
    "Source/BrsHw.c",
    "Source/BrsHwIntTb.c",
    "Source/BrsHwStartup.c",
    "Source/BrsMain.c",
    "Source/BrsMainStartup.c",
    #"Source/BrsMainVTT.c",
    "Source/BrsMain_Appl.c",
    "Source/BrsMain_Callout_Stubs.c",
    "Source/BswM_Callout_Stubs.c",
    "Source/BSW_Handler/BSW_Handler_MemMap.h",
    "Source/BSW_Handler/Rte.h",
    "Source/BSW_Handler/Rte_BSW_Handler.h",
    "Source/BSW_Handler/Rte_BSW_Handler_Type.h",
    "Source/BSW_Handler/Rte_Compiler_Cfg.h",
    "Source/BSW_Handler/Rte_DataHandleType.h",
    "Source/BSW_Handler/Rte_MemMap.h",
    "Source/BSW_Handler/Rte_Type.h",
    "Source/BSW_Handler/Rte_UserTypes.h",
    "Source/BSW_Handler.c",
    "Source/Dcm_Callout_Stubs.c",
    "Source/EcuM_Callout_Stubs.c",
    "Source/IoHwAb/IoHwAb_MemMap.h",
    "Source/IoHwAb/Rte.h",
    "Source/IoHwAb/Rte_Compiler_Cfg.h",
    "Source/IoHwAb/Rte_DataHandleType.h",
    "Source/IoHwAb/Rte_IoHwAb.h",
    "Source/IoHwAb/Rte_IoHwAb_Type.h",
    "Source/IoHwAb/Rte_MemMap.h",
    "Source/IoHwAb/Rte_Type.h",
    "Source/IoHwAb/Rte_UserTypes.h",
    "Source/IoHwAb.c",
    "Source/LightCtrl/LightCtrl_MemMap.h",
    "Source/LightCtrl/Rte.h",
    "Source/LightCtrl/Rte_Compiler_Cfg.h",
    "Source/LightCtrl/Rte_DataHandleType.h",
    "Source/LightCtrl/Rte_LightCtrl.h",
    "Source/LightCtrl/Rte_LightCtrl_Type.h",
    "Source/LightCtrl/Rte_MemMap.h",
    "Source/LightCtrl/Rte_Type.h",
    "Source/LightCtrl/Rte_UserTypes.h",
    "Source/LightCtrl.c",
    "Source/Os_Callout_Stubs.c",
    "Source/Rte_Hook.c",
    #"Source/Vtt_CustomVars_Cfg.h",
    #"Source/Vtt_CustomVars_InitCfg.c",
    #"Source/Vtt_stubs.c",
]

def prefix_for_each(prefix, list):
    return [prefix + x for x in list]

SOURCE_TARGETS = prefix_for_each("//ECU/BFC/Appl:Source/", SOURCE)
